### ISSUE TITLE
Not working with JDK 11 and SonarQube 8.0

### ISSUE THREAD

**Issue by Indigo744** [sleroy/sonar-slack-notifier-plugin#2]
**SonarQube** version :  8.0.0.29455
**CKS Slack Notifier** version : 2.5

Here is the error:
```
2019.12.12 13:26:19 INFO  ce[AW76Evfxm6xg_5sBOOFU][c.k.s.s.c.c.AbstractSlackNotifyingComponent] Constructor called, project slack channel config map constructed from general settings
2019.12.12 13:26:20 ERROR ce[AW76Evfxm6xg_5sBOOFU][o.s.c.t.CeWorkerImpl] Failed to execute task AW76Evfxm6xg_5sBOOFU
java.lang.IllegalStateException: Unable to load component class com.koant.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.containers.ImmutablePicoContainer.getComponent(ImmutablePicoContainer.java:40)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:718)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
	at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)
	at org.picocontainer.parameters.CollectionComponentParameter$1.resolveInstance(CollectionComponentParameter.java:139)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:141)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at org.sonar.core.platform.ComponentContainer.getComponentByType(ComponentContainer.java:281)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2848)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2472)
	at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:38)
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:167)
	at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:250)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:908)
	at com.koant.sonar.slacknotifier.extension.task.SlackHttpClient.<init>(SlackHttpClient.java:51)
	at com.koant.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask.<init>(SlackPostProjectAnalysisTask.java:35)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 48 more

```

Thanks.

**Comment by Indigo744** [comment]
Issue on original repo: https://github.com/kogitant/sonar-slack-notifier-plugin/issues/31

**Comment by Indigo744** [comment]
Sadly, I fail to see anything useful in the changelogs of SQ 8.0: https://docs.sonarqube.org/latest/setup/upgrade-notes/
Full release note: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10930&version=14962

**Comment by sleroy** [comment]
It looks like something linked with JDK 11 ?

**Comment by sleroy** [comment]
Seems the rest client okhttp3 has some issues with JDK11 (used by the plugin)

**Comment by Indigo744** [comment]
Interesting. 

I am sadly not very good in Java so I won't be able to help much in the code, but tell me if I can be of help.

Should I try to update JDK or something?

**Comment by sleroy** [comment]
No, I need to make a new release of the plugin with some upgraded dependencies.

I am producing a new version and will release it today. Please give me a feedback then if it solves your issue.

**Comment by sleroy** [comment]
Please try this version : https://github.com/sleroy/sonar-slack-notifier-plugin/releases/tag/2.6.0

Remove the older version.
and Install the new one in your plugin folder

**Comment by Indigo744** [comment]
Wow you are fast! I'll do it right away.
Although our build process takes approximately 30 minutes to complete... Sorry...

**Comment by Indigo744** [comment]
@sleroy  Sorry but I fail to find the JAR file?

**Comment by sleroy** [comment]
my bad, the artifact did not upload: Here is the link https://github.com/sleroy/sonar-slack-notifier-plugin/releases/download/2.6.0/cks-slack-notifier-2.6.0.jar

**Comment by Indigo744** [comment]
Build started, I'll let you know!  🤞

**Comment by Indigo744** [comment]
Well, everything went fine but the result was not sent to Slack 😞

**Comment by Indigo744** [comment]
In the log, there is this weird error:

```
2019.12.12 16:25:13 INFO  ce[AW76sQNp757ywNdbTWkx][c.k.s.s.c.c.AbstractSlackNotifyingComponent] SlackNotifierProp.CONFIG=[[]]
2019.12.12 16:25:13 INFO  ce[AW76sQNp757ywNdbTWkx][c.k.s.s.e.t.SlackPostProjectAnalysisTask] Slack notifier plugin disabled, skipping. Settings are [{CONFIG=, HOOK=, PROXY_IP=, INCLUDE_BRANCH=false, ENABLED=false, USER=SonarQube, PROXY_PORT=8080, PROXY_PROTOCOL=HTTP}; project specific channel config: {}]
2019.12.12 16:25:13 ERROR ce[AW76sQNp757ywNdbTWkx][o.s.c.t.s.ComputationStepExecutor] Execution of listener failed
java.lang.AbstractMethodError: Receiver class com.koant.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask does not define or inherit an implementation of the resolved method abstract getDescription()Ljava/lang/String; of interface org.sonar.api.ce.posttask.PostProjectAnalysisTask.
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:124)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It says plugin is disabled even though it is enabled in the configuration:
![image](https://user-images.githubusercontent.com/7137528/70725790-4f3e2d80-1cfd-11ea-9652-e8993c9e6639.png)

**Comment by sleroy** [comment]
This is another error. My plugin has been tested on the LTS 7.2+ version.
The version 8 is not yet supported.

Creates another issue please.

**Comment by Indigo744** [comment]
Why should I create another issue? This issue concerns SonarQube 8.0, as stated in the title.

Of course the version 8 is not yet supported. This is why this issue exists in the first place!

**Comment by jackemuk** [comment]
I am having the same issue running SonarQube 8.0. 

SonarQube version : 8.0.0.29455
CKS Slack Notifier version : 2.6.0

```
2019.12.19 17:09:25 INFO  ce[AW8fIphInpZ1RQ180HoG][c.k.s.s.c.c.AbstractSlackNotifyingComponent] SlackNotifierProp.CONFIG=[[]]
2019.12.19 17:09:25 INFO  ce[AW8fIphInpZ1RQ180HoG][c.k.s.s.e.t.SlackPostProjectAnalysisTask] Slack notifier plugin disabled, skipping. Settings are [{CONFIG=, HOOK=, PROXY_IP=, INCLUDE_BRANCH=false, ENABLED=false, USER=SonarQube, PROXY_PORT=8080, PROXY_PROTOCOL=HTTP}; project specific channel config: {}]
2019.12.19 17:09:25 ERROR ce[AW8fIphInpZ1RQ180HoG][o.s.c.t.s.ComputationStepExecutor] Execution of listener failed
java.lang.AbstractMethodError: Receiver class com.koant.sonar.slacknotifier.extension.task.SlackPostProjectAnalysisTask does not define or inherit an implementation of the resolved method 'abstract java.lang.String getDescription()' of interface org.sonar.api.ce.posttask.PostProjectAnalysisTask.
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:124)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2019.12.19 17:09:25 INFO  ce[AW8fIphInpZ1RQ180HoG][o.s.c.t.CeWorkerImpl] Executed task | project=vivoom-render2 | type=REPORT | branch=master | branchType=LONG | id=AW8fIphInpZ1RQ180HoG | submitter=admin | status=SUCCESS | time=6381ms
```

**Comment by sleroy** [comment]
> Why should I create another issue? This issue concerns SonarQube 8.0, as stated in the title.
> 
> Of course the version 8 is not yet supported. This is why this issue exists in the first place!

No need to argue. The issue you copy/pasted previously is not linked to SonarQube 8,0 but JDK11 and has been solved. There is another issue or rather a feature request to make the plugin compatible.  with SonarQube 8.0 and I will fix it as well.

**Comment by Indigo744** [comment]
@sleroy  sorry didn't mean to snap at you. I'll open a new issue.

**Comment by sleroy** [comment]
I have been working on your issue this week (I have already done some
commits).
I hope to release a new version next week, XMas gift :-)

Best,

Sylvain

**Comment by Indigo744** [comment]
Thank you so much 😸

**Comment by sleroy** [comment]
I am closing the ticket. I am not maintaing actively the plugin since the feature is defacto provided by SonarQube with their SonarJS plugin.

Thank you for your message and sorry for the inconvenience.
